In [3]:
using Knet, Images
include(Knet.dir("data/mnist.jl"))
xtrn,ytrn,xtst,ytst = mnist()
xtrn10x10 = zeros(Float32,10,10,1,60000)
xtst10x10 = zeros(Float32,10,10,1,10000)
@time for i in 1:60000; xtrn10x10[:,:,1,i] .= imresize(xtrn[5:24,5:24,1,i],(10,10)); end
@time for i in 1:10000; xtst10x10[:,:,1,i] .= imresize(xtst[5:24,5:24,1,i],(10,10)); end
Knet.save("mnist10x10.jld2","xtrn",reshape(xtrn10x10,100,:),"ytrn",ytrn,"xtst",reshape(xtst10x10,100,:),"ytst",ytst)

  0.212958 seconds (957.96 k allocations: 256.316 MiB, 6.18% gc time)
  0.035958 seconds (157.96 k allocations: 42.693 MiB, 7.33% gc time)


In [5]:
summary.(values(Knet.load("mnist10x10.jld2")))

4-element Array{String,1}:
 "100×60000 Array{Float32,2}"  
 "10000-element Array{UInt8,1}"
 "60000-element Array{UInt8,1}"
 "100×10000 Array{Float32,2}"  